# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('type_description', redactor.fields.RedactorField()),
            ],
        ),
    ]
