# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-01 15:08
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplemodel',
            name='type_description',
            field=redactor.fields.RedactorField(verbose_name='Text'),
        ),
    ]
